name: Build and Deploy Node.js Container

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Use the latest version of the checkout action.

      - name: Build and Push Docker Image
        run: |
          # Build a Docker image from the repository using the Dockerfile.
          docker build . -f Dockerfile -t my-image-name:${{ github.run_number }}
          
   
          # docker login -u USERNAME -p PASSWORD my-harbor-registry.example.com
          # docker push my-harbor-registry.example.com/my-image-name:${{ github.run_number }}
