name: Build and Publish in GitHub Package Registry

on:
  push:
    branches: [ "tagver" ]
  pull_request:
    branches: [ "tagver" ]
  #tags:
   # - 'v*'  

env:
  HARBOR_ROBOT_USERNAME: prod-harbor-robot@omnibase+write-omb-user
  REPO: harbor.maersk.io/omnibase/testimage/myapp
  VERSION: 0

jobs:
  build-and-push-image:                                     #There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:                                            #Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
      contents: read
      packages: write
      issues: write

    steps:
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Checkout Code
        uses: actions/checkout@v4                           # Use the latest version of the checkout action.
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: harbor.maersk.io
          username: ${{ env.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}
      
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: v1.0.0 # Optional fallback tag to use when no tag can be found    

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          #context: .
          push: false
          tags: |
            harbor.maersk.io/omnibase/testimage/myapp:latest
            harbor.maersk.io/omnibase/testimage/myapp:${{ steps.previoustag.outputs.tag }}

            

      #      harbor.maersk.io/omnibase/testimage/myapp:latest
      #      harbor.maersk.io/omnibase/testimage/myapp:
      
