name: Build and Deploy Node.js Container

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Use the latest version of the checkout action.

      - name: Build and Push Docker Image
        run: |
          # Build a Docker image from the repository using the Dockerfile.
          docker build . -f Dockerfile -t myapp:${{ github.run_number }}
          
           # Log in to Harbor using robot account credentials stored as GitHub secrets.
          docker login -u ${{ secrets.HARBOR_ROBOT_USERNAME }} --password-stdin ${{ secrets.HARBOR_ROBOT_PASSWORD }}  harbor.maersk.io

          # Push the Docker image to Harbor.
          docker push harbor.maersk.io/omnibase/testimage/[myapp:${{ github.run_number }}]
