name: Build and Publish in GitHub Package Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push-image:                                     #There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
    runs-on: ubuntu-latest

    permissions:                                            #Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4                           # Use the latest version of the checkout action.

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: harbor.maersk.io
          username: ${{ secrets.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.3.0
        with:
          branches: main
          tag_prefix: v
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: v${major}.${mminor}.$patch}-prereleases${increament}
          branch: HEAD
          use_branches: false
          version_from_branch: false
          version_format: ${major}.${minor}.${patch}
          bump_each_commit: false
          search_commit_body: false
          user_format_type: csv
          enable_prerelease_mode: false
          debug: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            harbor.maersk.io/omnibase/testimage/myapp
          tags: |
            # minimal
            type=match,pattern=\d.\d.\d
            # define match group
            type=match,pattern=v(.*),group=1
            # use custom value instead of git tag
            type=match,pattern=v(.*),group=1,value=v1.0.0

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
