name: Build and Publish in GitHub Package Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  tags:
      - 'v*'

env:
  HARBOR_ROBOT_USERNAME: prod-harbor-robot@omnibase+write-omb-user
  REPO: harbor.maersk.io/omnibase/testimage/myapp
  VERSION: 0

jobs:
  build-and-push-image:                                     #There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:                                            #Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
      contents: read
      packages: write
      issues: write

    steps:
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      
      - name: Checkout Code
        uses: actions/checkout@v4                           # Use the latest version of the checkout action.
        with:
          fetch-depth: 0

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: harbor.maersk.io
          username: ${{ env.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}
     
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.REPO }}
          tag-custom: latest
          tag-semver: |
            {{raw}}
          
      #- name: Tag Release (vX.Y.Z)
      #  run: |
      #    git tag ${{ steps.meta.outputs.tags }}
      #    #echo ${{ steps.meta.outputs.labels }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          #context: .
          push: false
          tags: |
            tags: ${{ steps.docker_meta.outputs.tags }}
            labels: ${{ steps.docker_meta.outputs.labels }}

      #      harbor.maersk.io/omnibase/testimage/myapp:latest
      #      harbor.maersk.io/omnibase/testimage/myapp:${{ steps.versioning.outputs.version_tag }}
