name: CI test
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
      issues: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  
      - name: Display GITHUB variables.
        run: |
          echo ${{ GITHUB.ref }}
          echo ${{ GITHUB.ref_name }}
          echo ${{ GITHUB.ref_protected }}
          echo ${{ GITHUB.ref_type }}

        