name: CI test

on:
  push:
    branches: [ "tagver" ]
  pull_request:
    branches: [ "tagver" ]
    #tags:
    #  - 'v*'  

jobs:
    build-and-push-image:                                     #There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
        runs-on: ubuntu-latest
        timeout-minutes: 15
    
        permissions:                                            #Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
            contents: read
            packages: write
            issues: write
    
        steps:
        - name: Create tag
          uses: actions/github-script@v5
          with:
            script: |
                github.rest.git.createRef({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    ref: 'refs/tags/',
                    sha: context.sha
                })