name: CI test
on:
  push:
    branches:
      - tagver
  pull_request:
    branches:
      - tagver
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
      issues: write
    steps:
        - name: Generate Docker Image Tags
          id: gen_tags
          run: |
            if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
                TAGS='["user/image:latest","user/image:'${GITHUB_REF/refs\/tags\//}'"]'
            else
                TAGS='["user/image:latest"]'
            fi
            echo '::set-output name=tags::'$TAGS

        - name: Build and Push Docker Image
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: .
            push: false
            tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
        
  display:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build-and-push-image

    steps:
        - name: print a value
          run: echo Hello from another hob
        